/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#faf8ff",
        "on-background": "#131b2e",
        "tertiary-fixed-dim": "#ffb77d",
        "on-secondary-fixed-variant": "#005137",
        "surface-container-low": "#f2f3ff",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-container": "#fc922b",
        "surface-container-highest": "#dae2fd",
        "surface-container-high": "#e2e7ff",
        "error-container": "#ffdad6",
        "surface-variant": "#dae2fd",
        "primary": "#00236f",
        "outline-variant": "#c5c5d3",
        "on-error": "#ffffff",
        "background": "#faf8ff",
        "on-surface-variant": "#3a3d4a",
        "on-secondary-fixed": "#002114",
        "secondary-fixed-dim": "#68dba9",
        "surface-tint": "#4059aa",
        "on-primary": "#ffffff",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "outline": "#64748b",
        "on-error-container": "#93000a",
        "on-primary-container": "#90a8ff",
        "primary-container": "#1e3a8a",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-secondary": "#ffffff",
        "secondary-container": "#82f5c1",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eaedff",
        "tertiary-fixed": "#ffdcc3",
        "on-primary-fixed-variant": "#264191",
        "tertiary-container": "#653400",
        "secondary-fixed": "#85f8c4",
        "secondary": "#006c4a",
        "on-primary-fixed": "#00164e",
        "inverse-primary": "#b6c4ff",
        "surface-bright": "#faf8ff",
        "on-secondary-container": "#00714e",
        "on-surface": "#0f172a",
        "primary-fixed-dim": "#b6c4ff",
        "tertiary": "#442100",
        "surface-dim": "#d2d9f4",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dce1ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.375rem",
        "xl": "0.625rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "1.25rem",
        "space-xs": "0.375rem",
        "space-lg": "1.75rem",
        "space-xl": "3rem",
        "space-md": "1.25rem",
        "gutter": "1.75rem",
        "gutter-mobile": "1.25rem",
        "space-sm": "0.75rem",
        "margin": "3rem"
      },
      fontSize: {
        "label-sm": [ "12px", { "lineHeight": "16px", "fontWeight": "600" } ],
        "headline-lg-mobile": [ "28px", { "lineHeight": "36px", "fontWeight": "600" } ],
        "display-lg-mobile": [ "34px", { "lineHeight": "42px", "fontWeight": "600" } ],
        "title-sm": [ "16px", { "lineHeight": "24px", "fontWeight": "600" } ],
        "body-sm": [ "14px", { "lineHeight": "22px", "fontWeight": "400" } ],
        "headline-md": [ "26px", { "lineHeight": "34px", "fontWeight": "600" } ],
        "headline-sm": [ "22px", { "lineHeight": "30px", "fontWeight": "500" } ],
        "title-md": [ "18px", { "lineHeight": "26px", "fontWeight": "600" } ],
        "label-lg": [ "15px", { "lineHeight": "20px", "fontWeight": "600" } ],
        "display-lg": [ "52px", { "lineHeight": "60px", "fontWeight": "600" } ],
        "headline-lg": [ "36px", { "lineHeight": "44px", "fontWeight": "600" } ],
        "body-lg": [ "18px", { "lineHeight": "28px", "fontWeight": "400" } ],
        "body-md": [ "16px", { "lineHeight": "26px", "fontWeight": "400" } ],
        "label-md": [ "13px", { "lineHeight": "18px", "fontWeight": "600" } ]
      },
      fontFamily: {
        "label-sm": [ "Public Sans", "sans-serif" ],
        "headline-lg-mobile": [ "Newsreader", "serif" ],
        "display-lg-mobile": [ "Newsreader", "serif" ],
        "title-sm": [ "Public Sans", "sans-serif" ],
        "body-sm": [ "Public Sans", "sans-serif" ],
        "headline-md": [ "Newsreader", "serif" ],
        "headline-sm": [ "Newsreader", "serif" ],
        "title-md": [ "Public Sans", "sans-serif" ],
        "label-lg": [ "Public Sans", "sans-serif" ],
        "display-lg": [ "Newsreader", "serif" ],
        "headline-lg": [ "Newsreader", "serif" ],
        "body-lg": [ "Public Sans", "sans-serif" ],
        "body-md": [ "Public Sans", "sans-serif" ],
        "label-md": [ "Public Sans", "sans-serif" ]
      }
    }
  },
  plugins: [],
}
